Description of remmean
Home > FastICA_25 > remmean.m
remmean
PURPOSE
REMMEAN - remove the mean from vectors
SYNOPSIS
function [newVectors, meanValue] = remmean(vectors);
DESCRIPTION
REMMEAN - remove the mean from vectors
 [newVectors, meanValue] = remmean(vectors);
 Removes the mean of row vectors.
 Returns the new vectors and the mean.
 This function is needed by FASTICA and FASTICAG
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
demosig
fastica FASTICA - Fast Independent Component Analysis
gui_cb
icaplot ICAPLOT - plot signals in various ways
SOURCE CODE
function [newVectors, meanValue] = remmean(vectors);
%REMMEAN - remove the mean from vectors
%
% [newVectors, meanValue] = remmean(vectors);
%
% Removes the mean of row vectors.
% Returns the new vectors and the mean.
%
% This function is needed by FASTICA and FASTICAG
% @(#)$Id: remmean.m,v 1.2 2003/04/05 14:23:58 jarmo Exp $
newVectors = zeros (size (vectors));
meanValue = mean (vectors')';
newVectors = vectors - meanValue * ones (1,size (vectors, 2));